#ifndef __S2_C2N_TXM_GUIDE_ENGINE_V3_1_H__
#define __S2_C2N_TXM_GUIDE_ENGINE_V3_1_H__



/*
* STRUCTURE S2_C2N_TXM_Guide_Engine_v3_1__CHANNELDATA
*/
#define CHANNELDATA__S2_C2N_TXM_Guide_Engine_v3_1_TITLE$_STRING_MAX_LEN 32
#define CHANNELDATA__S2_C2N_TXM_Guide_Engine_v3_1_ARTIST$_STRING_MAX_LEN 32
#define CHANNELDATA__S2_C2N_TXM_Guide_Engine_v3_1_SONG$_STRING_MAX_LEN 32
START_STRUCTURE_DEFINITION( S2_C2N_TXM_Guide_Engine_v3_1, CHANNELDATA )
{
   CREATE_STRING_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1, CHANNELDATA__TITLE$, CHANNELDATA__S2_C2N_TXM_Guide_Engine_v3_1_TITLE$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1, CHANNELDATA__TITLE$ );
   CREATE_STRING_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1, CHANNELDATA__ARTIST$, CHANNELDATA__S2_C2N_TXM_Guide_Engine_v3_1_ARTIST$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1, CHANNELDATA__ARTIST$ );
   CREATE_STRING_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1, CHANNELDATA__SONG$, CHANNELDATA__S2_C2N_TXM_Guide_Engine_v3_1_SONG$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1, CHANNELDATA__SONG$ );
   unsigned short CHANNELDATA__NUMBER;
   unsigned short CHANNELDATA__MAINCATEGORY;
   unsigned short CHANNELDATA__STATUS;
   short CHANNELDATA__SID;
};

/*
* STRUCTURE S2_C2N_TXM_Guide_Engine_v3_1__CATEGORYDATA
*/
#define CATEGORYDATA__S2_C2N_TXM_Guide_Engine_v3_1_CATNAME$_STRING_MAX_LEN 32
START_STRUCTURE_DEFINITION( S2_C2N_TXM_Guide_Engine_v3_1, CATEGORYDATA )
{
   CREATE_STRING_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1, CATEGORYDATA__CATNAME$, CATEGORYDATA__S2_C2N_TXM_Guide_Engine_v3_1_CATNAME$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1, CATEGORYDATA__CATNAME$ );
   unsigned short CATEGORYDATA__CATNUMBER;
};

/*
* STRUCTURE S2_C2N_TXM_Guide_Engine_v3_1__CATEGORYSTRUCTURE
*/
START_STRUCTURE_DEFINITION( S2_C2N_TXM_Guide_Engine_v3_1, CATEGORYSTRUCTURE )
{
   CREATE_INTARRAY1D( S2_C2N_TXM_Guide_Engine_v3_1, CATEGORYSTRUCTURE__TOTAL, 31 );;
   DECLARE_INTARRAY( S2_C2N_TXM_Guide_Engine_v3_1, CATEGORYSTRUCTURE__TOTAL );
   CREATE_INTARRAY2D( S2_C2N_TXM_Guide_Engine_v3_1, CATEGORYSTRUCTURE__MAP, 31, 255 );;
   DECLARE_INTARRAY( S2_C2N_TXM_Guide_Engine_v3_1, CATEGORYSTRUCTURE__MAP );
};


/*
* Constructor and Destructor
*/
int S2_C2N_TXM_Guide_Engine_v3_1_CHANNELDATA_Constructor ( START_STRUCTURE_DEFINITION( S2_C2N_TXM_Guide_Engine_v3_1, CHANNELDATA ) * me, int nVerbose );
int S2_C2N_TXM_Guide_Engine_v3_1_CHANNELDATA_Destructor ( START_STRUCTURE_DEFINITION( S2_C2N_TXM_Guide_Engine_v3_1, CHANNELDATA ) * me, int nVerbose );
int S2_C2N_TXM_Guide_Engine_v3_1_CATEGORYDATA_Constructor ( START_STRUCTURE_DEFINITION( S2_C2N_TXM_Guide_Engine_v3_1, CATEGORYDATA ) * me, int nVerbose );
int S2_C2N_TXM_Guide_Engine_v3_1_CATEGORYDATA_Destructor ( START_STRUCTURE_DEFINITION( S2_C2N_TXM_Guide_Engine_v3_1, CATEGORYDATA ) * me, int nVerbose );
int S2_C2N_TXM_Guide_Engine_v3_1_CATEGORYSTRUCTURE_Constructor ( START_STRUCTURE_DEFINITION( S2_C2N_TXM_Guide_Engine_v3_1, CATEGORYSTRUCTURE ) * me, int nVerbose );
int S2_C2N_TXM_Guide_Engine_v3_1_CATEGORYSTRUCTURE_Destructor ( START_STRUCTURE_DEFINITION( S2_C2N_TXM_Guide_Engine_v3_1, CATEGORYSTRUCTURE ) * me, int nVerbose );

/*
* DIGITAL_INPUT
*/
#define __S2_C2N_TXM_Guide_Engine_v3_1_POWERONFB_DIG_INPUT 0
#define __S2_C2N_TXM_Guide_Engine_v3_1_POWERINGONFB_DIG_INPUT 1
#define __S2_C2N_TXM_Guide_Engine_v3_1_SHOWCATLIST_DIG_INPUT 2
#define __S2_C2N_TXM_Guide_Engine_v3_1_SHOWCHANNELLIST_DIG_INPUT 3
#define __S2_C2N_TXM_Guide_Engine_v3_1_GENERATEFOCUSLIST_DIG_INPUT 4
#define __S2_C2N_TXM_Guide_Engine_v3_1_CONCATENATESTRINGS_DIG_INPUT 5
#define __S2_C2N_TXM_Guide_Engine_v3_1_CONTROL_OK_DIG_INPUT 6


/*
* ANALOG_INPUT
*/
#define __S2_C2N_TXM_Guide_Engine_v3_1_SHOWCATEGORYCHANNELS_ANALOG_INPUT 0
#define __S2_C2N_TXM_Guide_Engine_v3_1_CURRENTCHANNEL_ANALOG_INPUT 4
#define __S2_C2N_TXM_Guide_Engine_v3_1_PRESETMODEFB_ANALOG_INPUT 5

#define __S2_C2N_TXM_Guide_Engine_v3_1_ACTIVECHANNELNUMBERIN$_STRING_INPUT 3
#define __S2_C2N_TXM_Guide_Engine_v3_1_ACTIVECHANNELNUMBERIN$_STRING_MAX_LEN 4
CREATE_STRING_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1, __ACTIVECHANNELNUMBERIN$, __S2_C2N_TXM_Guide_Engine_v3_1_ACTIVECHANNELNUMBERIN$_STRING_MAX_LEN );

#define __S2_C2N_TXM_Guide_Engine_v3_1_GUIDEINFO$_BUFFER_INPUT 1
#define __S2_C2N_TXM_Guide_Engine_v3_1_GUIDEINFO$_BUFFER_MAX_LEN 20000
CREATE_STRING_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1, __GUIDEINFO$, __S2_C2N_TXM_Guide_Engine_v3_1_GUIDEINFO$_BUFFER_MAX_LEN );
#define __S2_C2N_TXM_Guide_Engine_v3_1_GUIDEREQUEST$_BUFFER_INPUT 2
#define __S2_C2N_TXM_Guide_Engine_v3_1_GUIDEREQUEST$_BUFFER_MAX_LEN 255
CREATE_STRING_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1, __GUIDEREQUEST$, __S2_C2N_TXM_Guide_Engine_v3_1_GUIDEREQUEST$_BUFFER_MAX_LEN );

#define __S2_C2N_TXM_Guide_Engine_v3_1_PRESETIN_ANALOG_INPUT 6
#define __S2_C2N_TXM_Guide_Engine_v3_1_PRESETIN_ARRAY_LENGTH 20

/*
* DIGITAL_OUTPUT
*/

#define __S2_C2N_TXM_Guide_Engine_v3_1_PRESETFB_DIG_OUTPUT 0
#define __S2_C2N_TXM_Guide_Engine_v3_1_PRESETFB_ARRAY_LENGTH 20

/*
* ANALOG_OUTPUT
*/
#define __S2_C2N_TXM_Guide_Engine_v3_1_NEWCHANNEL_ANALOG_OUTPUT 0
#define __S2_C2N_TXM_Guide_Engine_v3_1_PRESETMODEOUT_ANALOG_OUTPUT 1
#define __S2_C2N_TXM_Guide_Engine_v3_1_SATSIGNALSTRENGTHOUT_ANALOG_OUTPUT 2
#define __S2_C2N_TXM_Guide_Engine_v3_1_REPSIGNALSTRENGTHOUT_ANALOG_OUTPUT 3
#define __S2_C2N_TXM_Guide_Engine_v3_1_TUNED_CHANNEL_ICON_ANALOG_OUTPUT 4

#define __S2_C2N_TXM_Guide_Engine_v3_1_GUIDERESPONSE$_STRING_OUTPUT 5
#define __S2_C2N_TXM_Guide_Engine_v3_1_GUIDERESPONSE2$_STRING_OUTPUT 6
#define __S2_C2N_TXM_Guide_Engine_v3_1_GUIDERESPONSE3$_STRING_OUTPUT 7
#define __S2_C2N_TXM_Guide_Engine_v3_1_ACTIVATIONNUMBER$_STRING_OUTPUT 8
#define __S2_C2N_TXM_Guide_Engine_v3_1_GUIDEERRORMESSAGE_STRING_OUTPUT 9
#define __S2_C2N_TXM_Guide_Engine_v3_1_FOCUSLIST$_STRING_OUTPUT 10
#define __S2_C2N_TXM_Guide_Engine_v3_1_TUNEDCHANNELNAMEOUT$_STRING_OUTPUT 11
#define __S2_C2N_TXM_Guide_Engine_v3_1_TUNEDCHANNELCATEGORYOUT$_STRING_OUTPUT 12
#define __S2_C2N_TXM_Guide_Engine_v3_1_TUNEDCHANNELSONGOUT$_STRING_OUTPUT 13
#define __S2_C2N_TXM_Guide_Engine_v3_1_TUNEDCHANNELARTISTOUT$_STRING_OUTPUT 14
#define __S2_C2N_TXM_Guide_Engine_v3_1_TUNEDCHANNELNUMBEROUT$_STRING_OUTPUT 15
#define __S2_C2N_TXM_Guide_Engine_v3_1_DIAGNOSTICSTRINGOUT$_STRING_OUTPUT 16

#define __S2_C2N_TXM_Guide_Engine_v3_1_PRESETNAMEOUT$_STRING_OUTPUT 17
#define __S2_C2N_TXM_Guide_Engine_v3_1_PRESETNAMEOUT$_ARRAY_LENGTH 20

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/
CREATE_INTARRAY1D( S2_C2N_TXM_Guide_Engine_v3_1, __FULLLIST, 255 );;
CREATE_INTARRAY1D( S2_C2N_TXM_Guide_Engine_v3_1, __USERLIST, 255 );;


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/
CREATE_SIGNED_INTARRAY1D( S2_C2N_TXM_Guide_Engine_v3_1, __SID_LIST, 256 );;
CREATE_SIGNED_INTARRAY1D( S2_C2N_TXM_Guide_Engine_v3_1, __ICON_INDEX_LIST, 256 );;


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_C2N_TXM_Guide_Engine_v3_1_CATEGORY_SEARCH_TERMS_ARRAY_NUM_ELEMS 31
#define __S2_C2N_TXM_Guide_Engine_v3_1_CATEGORY_SEARCH_TERMS_ARRAY_NUM_CHARS 32
CREATE_STRING_ARRAY( S2_C2N_TXM_Guide_Engine_v3_1, __CATEGORY_SEARCH_TERMS, __S2_C2N_TXM_Guide_Engine_v3_1_CATEGORY_SEARCH_TERMS_ARRAY_NUM_ELEMS, __S2_C2N_TXM_Guide_Engine_v3_1_CATEGORY_SEARCH_TERMS_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/
#define __S2_C2N_TXM_Guide_Engine_v3_1_CHANNELS_STRUCT_MAX_LEN 255
CREATE_STRUCTURE_ARRAY( S2_C2N_TXM_Guide_Engine_v3_1, __CHANNELS, CHANNELDATA, __S2_C2N_TXM_Guide_Engine_v3_1_CHANNELS_STRUCT_MAX_LEN );
#define __S2_C2N_TXM_Guide_Engine_v3_1_CATEGORIES_STRUCT_MAX_LEN 31
CREATE_STRUCTURE_ARRAY( S2_C2N_TXM_Guide_Engine_v3_1, __CATEGORIES, CATEGORYDATA, __S2_C2N_TXM_Guide_Engine_v3_1_CATEGORIES_STRUCT_MAX_LEN );

START_GLOBAL_VAR_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __PRESETFB );
   DECLARE_IO_ARRAY( __PRESETIN );
   DECLARE_IO_ARRAY( __PRESETNAMEOUT$ );
   unsigned short __SEMAPHORE;
   unsigned short __SEMAPHORE2;
   unsigned short __LASTCATEGORY;
   unsigned short __LASTCHANNEL;
   unsigned short __TOTALCATEGORIESSTORED;
   unsigned short __TOTALCHANNELSSTORED;
   unsigned short __PRESETTOSAVE;
   unsigned short __REQUESTIDSAVINGPRESET;
   unsigned short __PRESETSAVETYPE;
   unsigned short __FULLLISTTOTALCHANNELS;
   unsigned short __USERLISTTOTALCHANNELS;
   unsigned short __HEADER;
   unsigned short __OFFSET;
   DECLARE_INTARRAY( S2_C2N_TXM_Guide_Engine_v3_1, __FULLLIST );
   DECLARE_INTARRAY( S2_C2N_TXM_Guide_Engine_v3_1, __USERLIST );
   DECLARE_SIGNED_INTARRAY( S2_C2N_TXM_Guide_Engine_v3_1, __SID_LIST );
   DECLARE_SIGNED_INTARRAY( S2_C2N_TXM_Guide_Engine_v3_1, __ICON_INDEX_LIST );
   DECLARE_STRING_ARRAY( S2_C2N_TXM_Guide_Engine_v3_1, __CATEGORY_SEARCH_TERMS );
   DECLARE_STRING_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1, __ACTIVECHANNELNUMBERIN$ );
   DECLARE_STRING_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1, __GUIDEINFO$ );
   DECLARE_STRING_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1, __GUIDEREQUEST$ );
   DECLARE_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1, CATEGORYSTRUCTURE, __CATEGORYMAP );
   DECLARE_STRUCT_ARRAY( S2_C2N_TXM_Guide_Engine_v3_1, __CHANNELS );
   DECLARE_STRUCT_ARRAY( S2_C2N_TXM_Guide_Engine_v3_1, __CATEGORIES );
};

START_NVRAM_VAR_STRUCT( S2_C2N_TXM_Guide_Engine_v3_1 )
{
};



#endif //__S2_C2N_TXM_GUIDE_ENGINE_V3_1_H__

